org: shara
app: nest-rest-api-with-serverless-lambda

service: nest-rest-api

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  profile: private_hara
  timeout: 30
  memorySize: 128

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
